# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jiychoi <jiychoi@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/06/21 19:20:50 by jiychoi           #+#    #+#              #
#    Updated: 2021/06/21 19:23:06 by jiychoi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC			=	gcc
CFLAGS		=	-Wall -Wextra -Werror
MFLAGS		=	-g3 -fsanitize=address
SRCS_SVR	=
SRCS_CLI	=
OBJS_SVR	=	$(SRCS_SVR:.c=.o)
OBJS_CLI	=	$(SRCS_CLI:.c=.o)
LIBFT		=	-L ./libft -lft
TARGET_SVR	=	minitalk_server
TARGET_CLI	=	minitalk_client
